"""
emit.py — Stage ⑤ Emit.

Serialise the normalized + validated model → world_model.generated.json:
fully resolved, `DO NOT EDIT` header, provenance stamp, deterministic key order.
Atomic write (tmp → os.replace). Derived, gitignored, fully regenerable.

Determinism: byte-identical across runs on identical inputs EXCEPT
`generator.generated_at` (and `docs_commit`). `--reproducible` fixes the
timestamp for the determinism gate.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path

from . import (ARTIFACT_VERSION, LOADER_VERSION, SUPPORTED_SCHEMA_VERSIONS, ast,
               resolution)
from .model import ParsedEntity, domain_of
from .registry import Registries

_HEADER = ("DO NOT EDIT — generated by the World Model loader (WM-3). "
           "Derived, gitignored, regenerable. Canonical source: "
           "04_ai_system/world_model/**/*.md")


def _rule_json(r) -> dict:
    base = {
        "token": r.token,
        "tier": r.tier,
        "severity_rank": r.severity_rank,
    }
    if r.kind == "fold" and r.fold:
        base["render_phrase_template"] = r.render_phrase
        base["kind"] = "fold"
        base["condition_source"] = r.condition_source
        base["fold"] = {
            "dedup_key": r.fold["dedup_key"],
            "emit_once": r.fold["emit_once"],
            "render_order": r.fold["render_order"],
            "render_phrase_prefix": r.fold["render_phrase_prefix"],
            "members": r.fold["members"],
            "per_signal": {k: ast.to_dict(v) for k, v in r.fold["per_signal"].items()},
        }
        return base
    base["render_phrase"] = r.render_phrase
    base["condition_source"] = r.condition_source
    base["ast"] = ast.to_dict(r.ast_node)
    base["reads_fields"] = ast.fields_read(r.ast_node)
    wins = ast.windows_used(r.ast_node)
    base["uses_window"] = wins[0] if wins else None
    base["uses_last_changed"] = ast.uses_last_changed(r.ast_node)
    return base


def _baseline_json(e: ParsedEntity) -> dict | None:
    b = e.baseline
    if b is None:
        return None
    if b["kind"] == "conditions":
        return {"kind": "conditions", "conditions": [ast.to_dict(c) for c in b["conditions"]]}
    return dict(b)


def _authorization_json(e: ParsedEntity) -> dict | None:
    if not e.writable:
        return None
    eid = (e.binding_signals.get("state") or {}).get("ha_entity")
    dom = domain_of(eid) if eid else None
    surface = [f"{dom}.turn_on", f"{dom}.turn_off"] if dom else []
    return {"declared_subset_of": "ha_call_service:D-12", "surface": surface, "target": eid}


def _entity_json(e: ParsedEntity) -> dict:
    fm = e.fm
    out: dict = {
        "id": e.id,
        "name": fm.get("name"),
        "region": e.region,
        "kind": e.kind,
        "status": e.status,
        "schema_version": fm.get("schema_version"),
    }
    if "priority" in fm:
        out["priority"] = fm["priority"]
    if e.writable:
        out["writable"] = True
        out["authorization"] = _authorization_json(e)
    if "boundary" in fm:
        out["boundary"] = fm["boundary"]
    if fm.get("archetype"):
        out["archetype"] = fm["archetype"]
        if e.archetype_applied:
            out["archetype_applied"] = e.archetype_applied
    if (bl := _baseline_json(e)) is not None:
        out["baseline"] = bl
    if e.binding_shape:
        out["binding"] = {"shape": e.binding_shape, "signals": e.binding_signals}
    if e.collector:
        out["collector"] = e.collector
    if "status_semantics" in fm:
        out["status_semantics"] = fm["status_semantics"]
    if e.depends_on:
        out["depends_on"] = e.depends_on
    if e.kind == "aggregate" or e.affects:
        out["affects"] = e.affects
    if "applies_to" in fm:
        ap = fm["applies_to"]
        out["applies_to"] = ({"shape": "roster", "members": ap} if isinstance(ap, list)
                             else {"shape": "selector", **ap})
    out["anomaly_rules"] = [_rule_json(r) for r in e.rules]
    out["evaluable"] = e.evaluable
    if e.kind == "aspect" and not e.evaluable:
        out["silent"] = True
        out["reserved_tokens"] = ["firmware_*"]
    out["provenance"] = {
        "file": str(e.file).split("world_model/", 1)[-1],
        "sha256": hashlib.sha256(e.file.read_bytes()).hexdigest(),
    }
    return out


def _registries_json(reg: Registries) -> dict:
    tokens = []
    for tok in reg.emission_order:
        t = reg.tokens[tok]
        tokens.append({"token": t.token, "tier": t.tier, "severity_rank": t.severity_rank,
                       "render_phrase": t.render_phrase, "status": t.status})
    for name, t in reg.tokens.items():
        if t.status != "active":
            tokens.append({"token": t.token, "tier": t.tier, "severity_rank": t.severity_rank,
                           "render_phrase": t.render_phrase, "status": t.status, "special": t.special})
    windows = {w.name: {"tz": w.tz, "start_min": w.start_min, "end_min": w.end_min,
                        "half_open": w.half_open} for w in reg.windows.values()}
    collectors = {c.collector_id: {"status": c.status, "exposes_last_changed": c.exposes_last_changed}
                  for c in reg.collectors.values()}
    return {"tokens": tokens, "windows": windows, "collectors": collectors}


def _graph_json(entities: list[ParsedEntity]) -> dict:
    depends = {e.id: e.depends_on for e in entities if e.depends_on}
    affects = {e.id: e.affects for e in entities if e.affects}
    part_of = {e.id: e.fm["part_of"] for e in entities if e.fm.get("part_of")}
    aspects: dict = {}
    for e in entities:
        if e.kind != "aspect":
            continue
        ap = e.fm.get("applies_to")
        if isinstance(ap, list):
            covers = [m["entity"] for m in ap if m.get("entity")]
            aspects[e.id] = {"kind": "roster", "member_count": len(ap),
                             "covers_entities": sorted(set(covers)),
                             "raw_bindings": sum(1 for m in ap if not m.get("entity"))}
        elif isinstance(ap, dict):
            aspects[e.id] = {"kind": "selector", **ap, "silent": True}
    return {"depends_on": depends, "affects": affects, "part_of": part_of, "aspects": aspects}


def build(entities: list[ParsedEntity], reg: Registries, *, docs_commit: str | None,
          generated_at: str) -> dict:
    entities = sorted(entities, key=lambda e: e.id)
    regions: dict[str, int] = {}
    for e in entities:
        regions[e.region] = regions.get(e.region, 0) + 1
    # ER-1: additive `resolution` registry. ARTIFACT_VERSION stays 1 (D-ER-7) —
    # additive keys are ignored by the evaluator, whereas a version bump would
    # silently degrade awareness instead of failing loud. Omitted entirely when no
    # entity carries aliases, so the artifact is unchanged for an alias-free model.
    res = resolution.build(entities)
    return {
        "_comment": _HEADER,
        "artifact_version": ARTIFACT_VERSION,
        "generator": {
            "loader_version": LOADER_VERSION,
            "generated_at": generated_at,
            "docs_commit": docs_commit,
            "supported_schema_versions": list(SUPPORTED_SCHEMA_VERSIONS),
            "source_root": "04_ai_system/world_model",
        },
        "registries": _registries_json(reg),
        "emission_order": list(reg.emission_order),
        "entities": {e.id: _entity_json(e) for e in entities},
        "graph": _graph_json(entities),
        **({"resolution": res} if res else {}),
        "stats": {
            "entities": len(entities),
            "active": sum(1 for e in entities if e.status == "active"),
            "evaluable": sum(1 for e in entities if e.evaluable),
            "regions": regions,
            "rules": sum(len(e.rules) for e in entities),
            "tokens_produced": len({r.token for e in entities for r in e.rules}),
        },
    }


def serialize(artifact: dict) -> str:
    return json.dumps(artifact, indent=2, ensure_ascii=False) + "\n"


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(content, encoding="utf-8")
    with open(tmp, "rb") as f:
        os.fsync(f.fileno())
    os.replace(tmp, path)
